spring:
  profiles:
    include: log
  application:
    name: miracle-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8082

logPath: log
logFileName: server-%d{yyyy-MM-dd}.%i.log
errorFileName: error-%d{yyyy-MM-dd}.%i.log