server:
  port: 8080
mybatis:
  mapper-locations: classpath*:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123

nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: 8b6860a9-092d-40a3-94c0-2f07b9c51f82